### ISSUE TITLE
Using more than 2 GPUs

### ISSUE THREAD

**Issue by igriffer** [src-d/kmcuda#10]
Hello! 
I have more than two GPUs and I want to run kmcuda on 3 and 4 devices. How can I do it?

**Comment by vmarkovtsev** [comment]
The defaults activate all the GPUs. Are there any problems?

**Comment by igriffer** [comment]
On devices 0 and 1 very heavy processes are started. How does the code behave in this case?

**Comment by vmarkovtsev** [comment]
The `device` argument gives you the fine control, please see the corresponding docs in README.md

**Comment by igriffer** [comment]
> device CUDA device OR-ed indices - usually 1. For example, 1 means using first device, 2 means second device, 3 means first and second device (2x speedup). Special value 0 enables all available devices.
Can I use only 3 or only 4 or only 3 and 4 devices?

**Comment by vmarkovtsev** [comment]
only 3

0100 = 0x8

only 4
1000 = 0x10

only 3 and 4

1100 = 0x18

**Comment by igriffer** [comment]
Ok, thank you!
