### ISSUE TITLE
Error in installing LightGBM GPU version for Windows.Error in -cmake.

### ISSUE THREAD

**Issue by asking28** [src-d/kmcuda#19]
![image](https://user-images.githubusercontent.com/29248466/27242850-a41faa9a-52fc-11e7-96f3-0aeb4bbd2064.png)

**Comment by vmarkovtsev** [comment]
Windows is the Satan's dreadful invention to suck life from my body and turn me crazy step by step.

Your compiler does not support OpenMP, it is written plain in the error message. If I were you, I would debug FindOpenMP.cmake, adding trace output and seeing what exactly goes wrong. I see that VC++ should support OpenMP, though the version is ancient.

And what's even funnier, you filed this issue on the wrong project. This is kmcuda, not LightGBM :laughing:

**Comment by asking28** [comment]
I was very confused about the issue. Thanks for the help.
