### ISSUE TITLE
predict method

### ISSUE THREAD

**Issue by draculayuan** [src-d/kmcuda#32]
Thanks for the lib! May I know if there is an method like kmeans_gpu.predict that i can use to predict which cluster does a new point belong to?

**Comment by vmarkovtsev** [comment]
Thank you very much for your feedback. Indeed, there is currently no function for new dots. I have received a few requests for this feature and will eventually add it. Stay tuned.

**Comment by draculayuan** [comment]
Thanks vmarkovstsev for you reply! May I know if there is any otherway to assign a new point to one of the existing clusters? For example, get centroids by applying kmeans_cuda on the training data, then use kmeans_cuda() again with "init = centroids" on the new point but not updating centroids? Then we take the assignment returned by kmeans_cuda as the predicted result?

**Comment by vmarkovtsev** [comment]
Yes, this will work.

**Comment by draculayuan** [comment]
Thanks! May I check how to make sure the kmeans_cuda wont update centroids?

**Comment by vmarkovtsev** [comment]
`kmeans_cuda` always returns the new centroids so you can easily check :smile: But it really does not update them with `tolerance=1`.

**Comment by draculayuan** [comment]
Ohh i see! Thank you so much!
