### ISSUE TITLE
Free memory in K-means

### ISSUE THREAD

**Issue by rvegamartinez** [src-d/kmcuda#35]
I have a doubt: when you allocate memory with **CUMALLOC**, do you free this memory before finishing the algorithm? I can not find **cudaFree** or something similar. I'm afraid if I use this algorithm (kmeans_cuda) in a code, it could overload the memory of the GPU

Thank you.

**Comment by vmarkovtsev** [comment]
No worries, smart pointers and RAII are used everywhere and the memory is guaranteed to be deallocated.
See https://github.com/src-d/kmcuda/blob/master/src/wrappers.h#L19

**Comment by rvegamartinez** [comment]
I haven't seen it! Thank you very much
