### ISSUE TITLE
Error: spurious trailing ‘%’ in format

### ISSUE THREAD

**Issue by RyanWangGit** [src-d/kmcuda#37]
I encountered this problem when compiling with gcc 5.3.0 and cuda 8.0.

```
/home/kmcuda/src/python.cc: In function ‘bool validate_features_size(uint32_t)’:
/home/kmcuda/src/python.cc:108:45: error: expected ‘)’ before ‘PRIu32’:
     sprintf(msg, "\"samples\": more than %" PRIu32 " features is not supported",
                                             ^~~~~~
/home/kmcuda/src/python.cc:109:26: error: spurious trailing ‘%’ in format [-Werror=format=]
```

[This page](https://stackoverflow.com/questions/8132399/how-to-printf-uint64-t-fails-with-spurious-trailing-in-format) explains why and by adding `#define __STDC_FORMAT_MACROS` at the begining of python.cc file I can compile successfully.

Also I tried gcc 6.3.0 and cuda 9.0 this problem still exists.

**Comment by vmarkovtsev** [comment]
I see, thanks for reporting. Will be happy to merge your PR; otherwise, I'll fix myself in a few days.
