### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by PatWalters** [src-d/kmcuda#39]
This package looks great, but I can't build it.  I'm getting this error when building on Ubuntu 14.04.5 with cuda 8.  Any help would be greatly appreciated.  Thanks. 

kmcuda/src/kmcuda.cc:206:0: error: ignoring #pragma omp simd [-Werror=unknown-pragmas]
       #pragma omp simd
 ^
kmcuda/src/kmcuda.cc:310:0: error: ignoring #pragma omp simd [-Werror=unknown-pragmas]
           #pragma omp simd reduction(+:dist_sum2)
 ^
cc1plus: all warnings being treated as errors

**Comment by vmarkovtsev** [comment]
Hi! What's your gcc version?

**Comment by PatWalters** [comment]
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4

**Comment by vmarkovtsev** [comment]
Right, [4.8 is too old](https://gcc.gnu.org/wiki/openmp). However, you can safelly comment out those pragmas, it will still work correctly.

**Comment by PatWalters** [comment]
Thanks, I'll upgrade my gcc and give it a try

**Comment by vmarkovtsev** [comment]
Assuming as fixed, please reopen if there is still an issue.
