### ISSUE TITLE
hi, How to get the distance from each sample to other sample in the cluster

### ISSUE THREAD

**Issue by luobo11** [src-d/kmcuda#40]
hi, How to get the distance from each sample to other sample in the cluster

**Comment by vmarkovtsev** [comment]
Do you mean all2all in a cluster? This is impossible in this library.

**Comment by luobo11** [comment]
yeah, the distance that each sample to others within a cluster. so , i  need to get the average of  distances   from each sample to each other sample in the cluster as each sample 's score. Is there any other way?

**Comment by vmarkovtsev** [comment]
E.g. numpy array manipulation using indexing after the assignments are done.
