### ISSUE TITLE
Installation Issue : subprocess.CalledProcessError: Command '('make', '-j8')' returned non-zero exit status 2

### ISSUE THREAD

**Issue by abhishek-mascon** [src-d/kmcuda#44]
Hello,

I am trying to set up this project to use K-man GPU implementation in Python.
In set up steps, I am getting Error while giving the

command: pip install git+https://github.com/src-d/kmcuda.git#subdirectory=src

Error:
Collecting git+https://github.com/src-d/kmcuda.git#subdirectory=src
Cloning https://github.com/src-d/kmcuda.git to /tmp/pip-NGyzQG-build
Requirement already satisfied: numpy in /usr/local/lib64/python2.7/site-packages (from libKMCUDA==6.2.1)
Installing collected packages: libKMCUDA
Running setup.py install for libKMCUDA ... error
Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-NGyzQG-build/src/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-PJz8TS-record/install-record.txt --single-version-externally-managed --compile:
running install
running build
running build_py
-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.4.3", minimum required is "3")
-- Found PythonLibs: /usr/lib64/libpython3.4m.so (found suitable version "3.4.3", minimum required is "3")
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/pip-NGyzQG-build/src
[ 16%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_transpose.cu.o
[ 33%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_kmeans.cu.o
[ 50%] Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o
nvcc fatal : Value 'sm_61' is not defined for option 'gpu-architecture'
nvcc fatal : Value 'sm_61' is not defined for option 'gpu-architecture'
nvcc fatal : Value 'sm_61' is not defined for option 'gpu-architecture'
CMake Error at KMCUDA_generated_transpose.cu.o.Release.cmake:207 (message):
Error generating
/tmp/pip-NGyzQG-build/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_transpose.cu.o

CMake Error at KMCUDA_generated_kmeans.cu.o.Release.cmake:207 (message):
  Error generating
  /tmp/pip-NGyzQG-build/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_kmeans.cu.o

CMake Error at KMCUDA_generated_knn.cu.o.Release.cmake:207 (message):
  Error generating
  /tmp/pip-NGyzQG-build/src/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_knn.cu.o

make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_transpose.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_kmeans.cu.o] Error 1
make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o] Error 1
make[1]: *** [CMakeFiles/KMCUDA.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pip-NGyzQG-build/src/setup.py", line 80, in <module>
    "Programming Language :: Python :: 3.6",
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 61, in run
    return orig.install.run(self)
  File "/usr/lib64/python2.7/distutils/command/install.py", line 604, in run
    self.run_command('build')
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/usr/lib64/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/pip-NGyzQG-build/src/setup.py", line 19, in run
    self._build()
  File "/tmp/pip-NGyzQG-build/src/setup.py", line 44, in _build
    check_call(("make", "-j%d" % cpu_count()))
  File "/usr/lib64/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('make', '-j8')' returned non-zero exit status 2

----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;file='/tmp/pip-NGyzQG-build/src/setup.py';f=getattr(tokenize, 'open', open)(file);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, file, 'exec'))" install --record /tmp/pip-PJz8TS-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-NGyzQG-build/src

Can anybody please help me to resolve this issue.
I am using cuda-7.5

Thanks,

**Comment by vmarkovtsev** [comment]
So the problem is that CUDA 7.5 does not support the compute capability (CC) 6.1.

You need to figure out your device's CC and override the default one with `export CUDA_ARCH=XX` - more info in https://github.com/src-d/kmcuda#building Not sure if environment variables are loaded in cmake automatically though, so alternatively you can hack https://github.com/src-d/kmcuda/blob/master/src/setup.py#L33

**Comment by vmarkovtsev** [comment]
Closing as there is no response. Feel free to reopen!
