### ISSUE TITLE
cuda error: the launch timed out and was terminated

### ISSUE THREAD

**Issue by zb0th** [src-d/kmcuda#67]
The dataset dim is: (581977, 2000)

Here are the logs. Same happens with a single GPU.

Issue goes away when using smaller dataset.

arguments: 1 0x7ffef9c84304 0.010 0.00 1 581977 2000 10000 1550770014 0 0 2 0x7f3704cb7010 0x7f3964fda010 0x310f210 (nil)
reassignments threshold: 5819
yinyang groups: 0
GPU #0 memory: used 4836229120 bytes (40.3%), free 7160725504 bytes, total 11996954624 bytes
GPU #1 memory: used 4820631552 bytes (40.2%), free 7176323072 bytes, total 11996954624 bytes
GPU #0 has 49152 bytes of shared memory per block
GPU #1 has 49152 bytes of shared memory per block
transposing the samples...
transpose <<<(18187, 63), (8, 32)>>> 581977, 2000, xyswap
performing kmeans++...
done            
too few clusters for this yinyang_t => Lloyd
plans: [(0, 290992), (290992, 290985)]
planc: [(0, 5000), (5000, 5000)]
cudaMemcpyFromSymbol(&my_changed, d_changed_number, sizeof(my_changed))
/tmp/pip-req-build-bqlfsbw6/src/kmeans.cu:705 -> the launch timed out and was terminated
kmeans_cuda_yy failed: the launch timed out and was terminated

**Comment by zb0th** [comment]
I'm wondering if this is actually an OOM error ? kind of confused with the **the launch timed out and was terminated** error message.

**Comment by zb0th** [comment]
After playing with diff dataset sizes, I'm now convinced this is an OOM error. It looks like the initial GPU memory usage can't be over 17% otherwise it is likely we will run into an OOM iterating.

**Comment by vmarkovtsev** [comment]
Consider using `yinyang_t=0` @zb0th - it disables the "yinyang" swagger and thus requires much much less memory.
