### ISSUE TITLE
Buffered input for very large dataset.

### ISSUE THREAD

**Issue by sharthZ** [src-d/kmcuda#7]
How about add buffered input for large datasets? 
~500M samples in 64 dimension into ~150M clusters for example.

**Comment by vmarkovtsev** [comment]
Yes,  it is in the plans (aka minibatch). Is the data sparse or dense? I planned to add sparse features support first.

**Comment by sharthZ** [comment]
I have dense data.

**Comment by vmarkovtsev** [comment]
This is for my future reference: `500Mx64x4=128GB`

**Comment by vmarkovtsev** [comment]
Facebook Research has recently released https://github.com/facebookresearch/faiss which is a very fast K-nn CUDA impl. It has K-means and allows to have datasets which do not fit into memory (it splits them and processes chunk by chunk). Faiss is focused on **very** large scale and is awesome so I will not address this issue.
