### ISSUE TITLE
building error on TITAN X

### ISSUE THREAD

**Issue by ibugs961** [src-d/kmcuda#8]
ubuntu14.04
CUDA8.0
cmake 3.7.2

``` shell
sudo cmake -DCMAKE_BUILD_TYPE=Release -DDISABLE_PYTHON=y -DCUDA_TOOLKIT_ROOT_DIR=/usr/local/cuda . && make
```

>  Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/cuda-workspace/kmcuda-master
Building NVCC (Device) object CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o
nvcc fatal   : Could not open output file /home/ubuntu/cuda-workspace/kmcuda-master/CMakeFiles/KMCUDA.dir//KMCUDA_generated_knn.cu.o.NVCC-depend
CMake Error at KMCUDA_generated_knn.cu.o.Release.cmake:222 (message):
  Error generating
  /home/ubuntu/cuda-workspace/kmcuda-master/CMakeFiles/KMCUDA.dir//./KMCUDA_generated_knn.cu.o
make[2]: *** [CMakeFiles/KMCUDA.dir/KMCUDA_generated_knn.cu.o] ERROR 1
make[1]: *** [CMakeFiles/KMCUDA.dir/all] ERROR 2
make: *** [all] ERROR 2

**Comment by vmarkovtsev** [comment]
```
nvcc fatal : Could not open output file /home/ubuntu/cuda-workspace/kmcuda-master/CMakeFiles/KMCUDA.dir//KMCUDA_generated_knn.cu.o.NVCC-depend
```
Permission problem?
```
touch /home/ubuntu/cuda-workspace/kmcuda-master/CMakeFiles/KMCUDA.dir//KMCUDA_generated_knn.cu.o.NVCC-depend
```
Did you mess up with `sudo`? Removed some directory by hand? Since TravisCI successfully builds the project on 14.04, the problem is on your side.

**Comment by ibugs961** [comment]
@vmarkovtsev Thank you very much.
