### ISSUE TITLE
peer access is not supported between these two devices

### ISSUE THREAD

**Issue by 448357739** [src-d/kmcuda#80]
I have 3 GPUs，I‘v already chosen gpu by 'torch.cuda.set_device(0)'.However ,I got several warnings.
warning: p2p 1 <-> 0 is impossible
warning: p2p 2 <-> 0 is impossible
warning: p2p 2 <-> 1 is impossible
warning: failed to enable p2p on gpu #0: peer access is not supported between these two devices
warning: failed to enable p2p on gpu #0: peer access is not supported between these two devices
warning: failed to enable p2p on gpu #1: peer access is not supported between these two devices
warning: failed to enable p2p on gpu #1: peer access is not supported between these two devices
warning: failed to enable p2p on gpu #2: peer access is not supported between these two devices
warning: failed to enable p2p on gpu #2: peer access is not supported between these two devices

**Comment by 448357739** [comment]
I missed the parameter  'device'.Sorry to bother you.

**Comment by kkissmart** [comment]
I still have this issue. how to set device? default 0 is using all the GPUs?
