### ISSUE TITLE
Does this project support windows?

### ISSUE THREAD

**Issue by km23630** [src-d/kmcuda#82]
I tried to build this project. but many errors occurred
I know what you said "Windows is the Satan's dreadful invention to suck life from my body and turn me crazy step by step."
but my project is focused on  only Windows and Python.
if this project not support Windows. probably I must use horribly slow Kmeans Algorithm.
Does this project support Windows? or Do you plan to support it in the future?

**Comment by vmarkovtsev** [comment]
Hi. Alas, Windows support is not planned atm. The code may or may not work, nobody tested. You can try to build and report here, although I will not help with solving the possible problems. Sorry.

**Comment by km23630** [comment]
> Hi. Alas, Windows support is not planned atm. The code may or may not work, nobody tested. You can try to build and report here, although I will not help with solving the possible problems. Sorry.

okay...

**Comment by smola** [comment]
Duplicate of https://github.com/src-d/kmcuda/issues/50
