### ISSUE TITLE
the number of features must be even in fp16 mode - error

### ISSUE THREAD

**Issue by samieti02** [src-d/kmcuda#86]
Hello dear Sir,

i got this error "the number of features must be even in fp16 mode", when i run this code.

```
k=10
# forCentroids = np.reshape(np.array([1,0], dtype='float32'),(2,1)) # (1)
forCentroids = kmeans_cuda(trainData, 2, metric="L2", verbosity=0, seed=3) # (2)

startTime = timer()

# Ytest_pred = knn_cuda(k, trainData, forCentroids , trainDataGroundtruth, verbosity=1, device=2) # where forCentroids is defined like in (1)
Ytest_pred = knn_cuda(k, trainData, forCentroids , forCentroids , verbosity=1, device=2) # where forCentroids is defined like in (2)

difftime = timer() - startTime
```

trainData is an np array of type float32 with the shape [100000,1]
trainDataGroundtruth is the groundtruth of train Data. An array of float32, that contains 1 and 0 value and has the shape [100000,]

I alwas get the error above. Can you please help me on this?

Thanks
Sami

**Comment by vmarkovtsev** [comment]
Indeed, the feature vector size must be even in fp16 mode, due to the way the optimizations are implemented. There is not much I can do here, unfortunately. You should switch to the regular fp32.

**Comment by samieti02** [comment]
Hello Sir,
thanks for the reply. I have changed the type of the data (trainData, forCentroids, ...) to "float16". But I always got the same error. What to do against that?

**Comment by vmarkovtsev** [comment]
You should ensure that the number of your features is even. That is, `x % 2 == 0`.

**Comment by samieti02** [comment]
ok, lets  say we have an 3D image 50x50x50 with pixel float values and the groundtruth with values 0 and 1, for 2 clusters. 
To solve it, I would reshape the arrays like this [75000, 1] => 75000 rows for sample and 1 column for feature. Thats means I would have , 1 column % 2 # 1. What is another way, maybe better to solve the problem or reshape the arrays to solve it?

The parameters `assignments` can correspond to the groundtruth data => [number of samples,] ?

**Comment by vmarkovtsev** [comment]
The second way is to work with float32. There is no third way for this library.

**Comment by samieti02** [comment]
And this is what I've done at first, as above. First, the data type was float32. And then I changed it to float16. 

I had than the problem with the number of features. This is why I asked about the shape of the arrays?

```
samples: [75000, 1]    => [0.231569547,
                           2,138494892,
                           ...,
                           0.932583493] 
```

```
centroids: [2, 1]      => [1,
                           0]
```

```
assignments: [75000,]  => [1,
                           1,
                           ...,
                           0] 
```

**Comment by samieti02** [comment]
Hello Sir,
can you tell me please, how i can make it work with my own data? The installation, was not so easy. Now  I encounter the problem with the data

I have: np.arrays with type float32
x_train  [5000, 1]   [n_samples, n_features]
x_test   [5000, 1]
====
y_train  [1000, 1]
y_test   [1000, 1]

How can I use these data with the method knn ?

Thanks sir

**Comment by samieti02** [comment]
Hello Sir ,

Can you please help me with that ?
if you have for example e.g 
20 data images of size 50x50x50 for training (float 32)
20 label images of size 50x50x50 for training (float 32)

5 data images of size 50x50x50 for testing (float 32)
5 label images of size 50x50x50 for testing (float 32)

How can we use knn (python) with the data?

Thanks
