### ISSUE TITLE
[FEATURE REQUEST] Support for sparse matrices

### ISSUE THREAD

**Issue by TyLeRRR** [src-d/kmcuda#94]
How hard would it be to add the support for dense matrices?

Currently using `TfIdfVectorizer.fit_transform()` which returns a sparse matrix. 
I could use the `X.toarray()` and convert sparse to dense, but for huge datasets, it can require 700+GB of RAM.

**Comment by vmarkovtsev** [comment]
You mean support sparse matrices, right?

**Comment by TyLeRRR** [comment]
Nope. Support for dense matrices.

Here is method that I am using from sklearn:
```python
    def fit_transform(self, raw_documents, y=None):
        """Learn vocabulary and idf, return term-document matrix.

        This is equivalent to fit followed by transform, but more efficiently
        implemented.

        Parameters
        ----------
        raw_documents : iterable
            an iterable which yields either str, unicode or file objects

        Returns
        -------
        X : sparse matrix, [n_samples, n_features]
            Tf-idf-weighted document-term matrix.
        """
        self._check_params()
        X = super().fit_transform(raw_documents)
        self._tfidf.fit(X)
        # X is already a transformed view of raw_documents so
        # we set copy to False
        return self._tfidf.transform(X, copy=False)
```

By declaring the vectorizer:
```python
vectorizer = TfidfVectorizer(
            min_df=min_document_frequency,
            use_idf=True,
            dtype=np.float32,
            ngram_range=(1, 1)
        )
```
And
```python 
x_train=vectorizer.fit_transform(cleaned_documents)
```
When I feed the `x_train` to `kmeans_cuda(...)`, I receive the error  `"samples" must be a 2D float32 or float16 numpy array`. Converting `x_train` to dense resolves the issue.

**Comment by vmarkovtsev** [comment]
But kmcuda works with precisely dense matrices...

**Comment by TyLeRRR** [comment]
omg. I am so dumb. I have found my bug. sry and thank you one more time @vmarkovtsev .

**Comment by TyLeRRR** [comment]
> You mean support sparse matrices, right?

I have the same question but for sparse. How time consuming and hard would it be to add this feature to kmcuda?

**Comment by TyLeRRR** [comment]
Hi @vmarkovtsev . I'd really like to get your answer on my last question. 

I don't have 3TB of RAM for dense matrix representation.
My use case is 8 mill. samples with 100k features. I run sklearn KMeans mostly with 8-130 clusters.
I hope kmcuda would drastically reduce the clustering time. 

Thanks for your time!

**Comment by vmarkovtsev** [comment]
Supporting the sparse input is the same effort as rewriting 80% of the project :smile: 

Are you sure that kmeans will work well for 100k sparse features? This seems like a classic case of the curse of dimensionality.

**Comment by TyLeRRR** [comment]
> Supporting the sparse input is the same effort as rewriting 80% of the project

oh... sad to hear that. But thanks for the answer.

> Are you sure that kmeans will work well for 100k sparse features?

what do you mean by that? We are currently pretty satisfied we the results. We run multiple kmeans, as I said 8-130 clusters, and for each run, we calculate a silhouette score - to determine the most optimal k. The only downside is time.
