### ISSUE TITLE
Can't install on Google colab

### ISSUE THREAD

**Issue by j-bac** [src-d/kmcuda#98]
I would like to try the package on Colab but I didn't manage to install it with:
`!CUDA_ARCH=75 pip install git+https://github.com/src-d/kmcuda.git#subdirectory=src`
or
`!git clone https://github.com/src-d/kmcuda
!cd kmcuda/src && python setup.py install`

error log:
 'CMake Error at /usr/local/lib/python2.7/dist-packages/cmake/data/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):',
 '  Could NOT find CUDA (missing: CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (found',
 '  version "10.0")'

**Comment by vmarkovtsev** [comment]
Hi @j-bac please refer to [Building](https://github.com/src-d/kmcuda#building). There is an env var that you should define.

Closing this...
